// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.Models;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(ProyectoDbContext))]
    [Migration("20260702192110_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Proyecto.Models.Consultor", b =>
                {
                    b.Property<int>("ConsultorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreConsultor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TarifaHora")
                        .HasColumnType("REAL");

                    b.HasKey("ConsultorId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Consultores");
                });

            modelBuilder.Entity("Proyecto.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Presupuesto")
                        .HasColumnType("REAL");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Proyecto.Models.Consultor", b =>
                {
                    b.HasOne("Proyecto.Models.Proyecto", "ProyectoAsignado")
                        .WithMany("ConsultorAsignado")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProyectoAsignado");
                });

            modelBuilder.Entity("Proyecto.Models.Proyecto", b =>
                {
                    b.Navigation("ConsultorAsignado");
                });
#pragma warning restore 612, 618
        }
    }
}
