// <auto-generated />
using Ejercicio1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejercicio1.Migrations
{
    [DbContext(typeof(CarreraDbContext))]
    partial class CarreraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ejercicio1.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CarreraId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Ejercicio1.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarreraECarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstudianteId");

                    b.HasIndex("CarreraECarreraId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Ejercicio1.Estudiante", b =>
                {
                    b.HasOne("Ejercicio1.Carrera", "CarreraE")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarreraECarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarreraE");
                });

            modelBuilder.Entity("Ejercicio1.Carrera", b =>
                {
                    b.Navigation("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
