// <auto-generated />
using Ejercicio1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejercicio1.Migrations
{
    [DbContext(typeof(AdopcionDbContext))]
    partial class AdopcionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ejercicio1.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DuenoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.HasKey("AnimalId");

                    b.HasIndex("DuenoId");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("Ejercicio1.Models.Dueno", b =>
                {
                    b.Property<int>("DuenoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DuenoId");

                    b.ToTable("Duenos");
                });

            modelBuilder.Entity("Ejercicio1.Models.Animal", b =>
                {
                    b.HasOne("Ejercicio1.Models.Dueno", "Dueno")
                        .WithMany("Animales")
                        .HasForeignKey("DuenoId");

                    b.Navigation("Dueno");
                });

            modelBuilder.Entity("Ejercicio1.Models.Dueno", b =>
                {
                    b.Navigation("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
