// <auto-generated />
using Ajedrez.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ajedrez.Migrations
{
    [DbContext(typeof(AjedrezDbContext))]
    partial class AjedrezDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Ajedrez.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClubNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClubSede")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClubId");

                    b.ToTable("Clubes");
                });

            modelBuilder.Entity("Ajedrez.Models.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JugadorCategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JugadorRankingFide")
                        .HasColumnType("INTEGER");

                    b.HasKey("JugadorId");

                    b.HasIndex("ClubId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Ajedrez.Models.Jugador", b =>
                {
                    b.HasOne("Ajedrez.Models.Club", "JugadorClub")
                        .WithMany("ClubJugadores")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JugadorClub");
                });

            modelBuilder.Entity("Ajedrez.Models.Club", b =>
                {
                    b.Navigation("ClubJugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
